/*
 *      Copyright (c) 2025 Bacancy System Pvt Ltd.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *      @author: BACANCY SYSTEMS PVT. LTD. (Developer: Vivek pal) 
 *      Date:    JAN 2025
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of Bacancy System Pvt. Ltd.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise
 *      duplicated and the information herein may not be used,
 *      disseminated or otherwise disclosed, except with the prior
 *      written consent of Bacancy System Pvt. Ltd.
 *
 */
 
#ifndef GW_TRDP_PD_H
#define GW_TRDP_PD_H
 
/***********************************************************************
 * Include Header Files
 **********************************************************************/
#include "trdp_if_light.h"
#include "vos_thread.h"
#include "vos_sock.h"
#include "vos_utils.h"
#include <ifaddrs.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <pthread.h>
#include <stdbool.h>
#include "GW_common.h"

/***********************************************************************
 * CONSTANTS
 **********************************************************************/
#define MAX_PD_COMID            15U
#define DATA_MAX                1432U
#define TRDP_FRAME_PERAMETER    214U
#define PD_PP_DATA_READY        1U
#define PD_PP_DATA_NOT_READY    0U
#define PD_PP_DATA_RECIVE       1U
#define PD_PP_DATA_NOT_RECIVE   0U
#define DEF_EER_STRING          "No data available"


#define PD_DATA_SET             1000U
#define PD_DATA_FRAME_MEMBER    16U


/***********************************************************************
* TYPES
***********************************************************************/

typedef enum 
{
    MSG_TYPE_PD_DATA          = TRDP_MSG_PD,          /* Pd Data        0x5064u */
    MSG_TYPE_PD_REQUEST_REPLY = TRDP_MSG_PP,          /* Pd Pull Reply  0x5070u */
    MSG_TYPE_PD_REQUEST       = TRDP_MSG_PR,          /* Pd Request     0x5072u */
    MSG_TYPE_PD_ERROR         = TRDP_MSG_PE           /* Pd Error       0x5065u */
} PACKED msgPdType_e;

typedef enum
{
    NO_ERROR                   = 0,
    RECIVED_FRAME_SIZE_IS_LESS = 1,
    RECIVED_BUFFER_IS_EMPTY    = 2
}PACKED msgPdErr_e;

/* Configuration for TRDP PD  message Type */
typedef struct trdpPdMsgConfig
{
    bool        bEnable;
    uint32_t    ui32MvbId;
    uint32_t    ui32SendComId;
    uint32_t    ui32TrdpPollIntervel;  /* time is in microseconds */
    uint32_t    ui32TrdpDestIp;
    uint32_t    ui32TrdpSrcIp1;
    uint32_t    ui32TrdpSrcIp2;
    TRDP_PUB_T  stPubHandle;
    TRDP_SUB_T  stSubHandle;
    uint8_t     ui8TrdpMsgBuff[DATA_MAX + TRDP_FRAME_PERAMETER];
    uint16_t    ui16TrdpMsgDataLen;
    uint8_t     ui8newData;
    msgPdType_e eMsgPdType;
} trdpPdMsgConfig_t;

typedef struct trdpPdMsg
{
    TRDP_PD_INFO_T stPdMsg;
    uint8_t        pui8TrdpMsg[DATA_MAX];
    uint16_t       ui16TrdpMsgLen;
}  PACKED trdpPdMsg_t;


/* X macrp for Trdp Pd configuration  */
/*   <CONFIGURATION No>  <          ENABLE OR DISABLE              >  <                   CONFIGURATION COM ID         >   <                    Trdp interval                     >   <              DESTINATION IP ADDRESS            >   <                SOURCE IP ADDRESS               >   <                Source IP ADDRESS              >   <        PUBLISH HANDEL                        >   <  SUBSCRIBER HANDEL                          >   <                TRDP MESSAGE BUFFER             >   <               TRDP MESSAGE LENGTH                  >   <            NEW DATA RECIVED                >   <                    TRDPMSG TYPE             >*/ 
#define TRDP_PD_MSG_CONFIG \
    X(TRDP_PD_CONFIG_1  , stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_1  ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_2  , stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_2  ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_3  , stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_3  ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_4  , stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_4  ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_5  , stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_5  ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_6  , stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_6  ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_7  , stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_7  ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_8  , stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_8  ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_9  , stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_9  ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_10 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_10 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_11 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_11 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_12 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_12 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_13 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_13 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_14 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_14 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_15 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_15 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_16 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_16 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_17 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_17 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_18 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_18 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_19 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_19 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_20 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_20 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_21 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_21 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_22 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_22 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_23 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_23 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_24 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_24 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_25 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_25 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_26 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_26 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_27 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_27 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_28 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_28 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_29 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_29 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_30 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_30 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_31 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_31 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_32 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_32 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_33 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_33 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_34 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_34 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_35 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_35 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_36 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_36 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_37 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_37 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_38 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_38 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_39 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_39 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_40 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_40 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_41 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_41 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_42 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_42 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_43 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_43 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_44 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_44 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_45 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_45 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_46 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_46 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_47 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_47 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_48 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_48 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_49 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_49 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_50 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_50 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_51 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_51 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_52 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_52 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_53 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_53 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_54 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_54 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_55 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_55 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_56 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_56 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_57 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_57 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_58 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_58 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_59 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_59 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_60 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_60 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_61 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_61 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_62 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_62 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_63 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_63 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_64 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_64 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_65 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_65 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_66 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_66 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_67 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_67 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_68 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_68 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_69 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_69 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_70 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_70 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_71 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_71 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_72 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_72 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_73 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_73 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_74 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_74 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_75 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_75 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_76 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_76 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_77 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_77 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_78 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_78 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_79 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_79 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_80 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_80 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_81 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_81 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_82 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_82 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_83 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_83 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_84 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_84 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_85 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_85 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_86 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_86 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_87 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_87 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_88 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_88 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_89 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_89 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_90 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_90 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_91 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_91 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_92 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_92 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_93 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_93 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_94 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_94 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_95 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_95 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_96 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_96 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_97 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_97 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_98 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_98 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_99 , stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_99 ].eMsgPdType ) \
    X(TRDP_PD_CONFIG_100, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_100].eMsgPdType ) \
    X(TRDP_PD_CONFIG_101, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_101].eMsgPdType ) \
    X(TRDP_PD_CONFIG_102, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_102].eMsgPdType ) \
    X(TRDP_PD_CONFIG_103, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_103].eMsgPdType ) \
    X(TRDP_PD_CONFIG_104, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_104].eMsgPdType ) \
    X(TRDP_PD_CONFIG_105, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_105].eMsgPdType ) \
    X(TRDP_PD_CONFIG_106, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_106].eMsgPdType ) \
    X(TRDP_PD_CONFIG_107, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_107].eMsgPdType ) \
    X(TRDP_PD_CONFIG_108, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_108].eMsgPdType ) \
    X(TRDP_PD_CONFIG_109, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_109].eMsgPdType ) \
    X(TRDP_PD_CONFIG_110, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_110].eMsgPdType ) \
    X(TRDP_PD_CONFIG_111, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_111].eMsgPdType ) \
    X(TRDP_PD_CONFIG_112, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_112].eMsgPdType ) \
    X(TRDP_PD_CONFIG_113, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_113].eMsgPdType ) \
    X(TRDP_PD_CONFIG_114, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_114].eMsgPdType ) \
    X(TRDP_PD_CONFIG_115, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_115].eMsgPdType ) \
    X(TRDP_PD_CONFIG_116, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_116].eMsgPdType ) \
    X(TRDP_PD_CONFIG_117, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_117].eMsgPdType ) \
    X(TRDP_PD_CONFIG_118, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_118].eMsgPdType ) \
    X(TRDP_PD_CONFIG_119, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_119].eMsgPdType ) \
    X(TRDP_PD_CONFIG_120, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_120].eMsgPdType ) \
    X(TRDP_PD_CONFIG_121, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_121].eMsgPdType ) \
    X(TRDP_PD_CONFIG_122, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_122].eMsgPdType ) \
    X(TRDP_PD_CONFIG_123, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_123].eMsgPdType ) \
    X(TRDP_PD_CONFIG_124, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_124].eMsgPdType ) \
    X(TRDP_PD_CONFIG_125, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_125].eMsgPdType ) \
    X(TRDP_PD_CONFIG_126, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_126].eMsgPdType ) \
    X(TRDP_PD_CONFIG_127, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_127].eMsgPdType ) \
    X(TRDP_PD_CONFIG_128, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_128].eMsgPdType ) \
    X(TRDP_PD_CONFIG_129, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].bEnable, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].ui32MvbId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].ui32SendComId, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].ui32TrdpPollIntervel, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].ui32TrdpDestIp, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].ui32TrdpSrcIp1, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].ui32TrdpSrcIp2, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].stPubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].stSubHandle, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].ui8TrdpMsgBuff, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].ui16TrdpMsgDataLen, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].ui8newData, stTrdpPdMsgConfig[TRDP_PD_CONFIG_129].eMsgPdType ) \

enum
{
    #define X(TRDP_MSGID, ENABLE, MVBID, COMID, INTERVAL, DEST_IP, SRCIP_1, SRCIP_2, HANDLER_PUB, HANDLER_SUB, MSG_BUFF, MSG_LEN, NEW_DATA, MSG_TYPE ) TRDP_MSGID,
        TRDP_PD_MSG_CONFIG
    #undef X
};



/***********************************************************************
* PUBLIC VARIABLES 
***********************************************************************/
/* Configuration for the Pd Message type */
extern trdpPdMsgConfig_t stTrdpPdMsgConfig[129];

extern TRDP_DATASET_T  gDataSetPd;

/***********************************************************************
* PUBLIC FUNCTION PROTOTYPES
***********************************************************************/
/**
 * @brief 
 * 
 * @param arg 
 * @return void* 
 */
void* pvEthTrdp(void* arg);

/**
 * @brief 
 * 
 * @param pRefCon 
 * @param appHandle 
 * @param pMsg 
 * @param pData 
 * @param dataSize 
 */
void pdCallback(void *pRefCon, TRDP_APP_SESSION_T appHandle, const TRDP_PD_INFO_T *pMsg, 
                UINT8 *pData, UINT32 dataSize);

/**
 * @brief update the Trdp Queue for sending pd data and pd reply and also update the application message buffer 
 * 
 * @param pu8DataBuff 
 * @param u32DataSize 
 * @param appHandle 
 * @return TRDP_ERR_T 
 */
TRDP_ERR_T eSendTrdpPdData(trdpPdMsg_t *stPdTrdpData, uint32_t u32DataSize, TRDP_APP_SESSION_T appHandle );

/**
 * @brief Init Trdp pd stack as per the configuration
 * 
 * @return TRDP_ERR_T 
 */
TRDP_ERR_T eInitTrdpPdStack(void);


/***********************************************************************
* END OF FILE
***********************************************************************/
#endif
